// <auto-generated />
namespace MedAgenda.CORE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class KarenFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KarenFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201511120109542_KarenFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
